### ISSUE TITLE
Image class needed

### ISSUE THREAD

**Issue by CrikeeIP** [CrikeeIP/OPTICS-Clustering#2]
Hi.
The dependency on CImg bugs me, since the only part needed is drawing a graph into an image and saving that image.
Could someone provide an Image class (simple rgb-image suffices) with the following API:
- Create an image with a given size
- Set single pixels in an image
- Given two points, draw a line segment into that image
- Optionally: take a set of values (a graph) and draw these values into an image.
- Save image to disk

Ingo

**Comment by Dobiasd** [comment]
I wrote a [very minimalistic image class](https://gist.github.com/Dobiasd/ec8d4567c52b9da0ff44670e1e9c7dfe). It supports only bgr images and can save only in [ppm format](http://netpbm.sourceforge.net/doc/ppm.html). It does not provide line drawing or graphs, but perhaps you can build upon it.
If you want to, I can create a PR.

**Comment by CrikeeIP** [comment]
Looks perfect. Thanks a lot.

**Comment by CrikeeIP** [comment]
Merged.
Thanks.
