### ISSUE TITLE
Does not compile under MSVC2017 since 17755c784840e75a5a4cc26d5f62b83c85d12350.

### ISSUE THREAD

**Issue by grefab** [CrikeeIP/OPTICS-Clustering#4]
radius_search (in particular [this](https://github.com/CrikeeIP/OPTICS-Clustering/blob/fdeb0e1e5be092f2b59e65cc40021a9a0796bdda/include/optics/optics.hpp#L306)) produces an error in MSVC2017. Seems like MS's implementation of `std::upper_bound` and `std::lower_bound` is not able to work with `std::pair` as comparison element.

Please find the complete error messages [here](https://gist.github.com/grefab/c7975909991510606455002a16f129c0).

**Comment by CrikeeIP** [comment]
Fixed by replacing radius search with nanoflann. [Commit](cfade23231635edb675158f80ffa0ad8511f5e4e)
